env:
  - name: ENV
    value: "qa"
  - name: GPU_ENABLED
    value: "1"
  - name: UI_THEME
    value: "light"
  - name: CACHE_SIZE
    value: "2048kb"
  - name: PAGE_LIMIT
    value: "25"
  - name: SORTING
    value: "ascending"    
  - name: N_BUCKETS
    value: "42"
  - name: ENV_TYPE
    value: non-prod
  - name: PAYPAL_URL
    value: staging2.paypal.com
  - name: DB_USER
    value: non-prod-user
  - name: DB_PASSWORD
    value: non-prod-password

replicaCount: 3

fullnameOverride: qa-simple-helm-2

service: {
  type: NodePort,
  nodePort: 31000
}