apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-eu-simple-env
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:  
  project: gitops-helm-promotion
  source:
    chart: simple-env-chart
    repoURL: 'https://github.com/lloydsmithjr03/simple-env-chart'
    targetRevision: 1.0.0
    helm:
      releaseName: prod-eu-simple-env
      valueFiles:
        - '../../prod-eu/values.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod-eu
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
