apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-eu-simple-env-helm-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:  
  project: gitops-helm-promotion
  source:
    path: kustomized_helm/overlays/prod-eu
    repoURL: https://github.com/lloydsmithjr03/gitops-helm-promotion
    targetRevision: HEAD
    plugin:
      name: kustomized-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod-helm-2
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
