apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-us-simple-env-helm-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:  
  project: gitops-helm-promotion
  source:
    chart: nginx
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.0.0
    helm:
      releaseName: prod-us-simple-env-helm-2
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod-helm-2
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
