apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa-simple-env
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: 'in-cluster'
    namespace: qa
  project: gitops-helm-promotion
  source:
    chart: simple-env-chart
    repoURL: 'https://github.com/lloydsmithjr03/simple-env-chart'
    targetRevision: 1.0.0
    helm:
      releaseName: qa-simple-env
      valueFiles:
        - '../../qa/values.yaml'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true