apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa-simple-env-helm-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: 'in-cluster'
    namespace: qa-helm-2
  project: gitops-helm-promotion
  source:
    chart: bitnami/nginx
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.0.0
    helm:
      releaseName: qa-simple-env-helm-2
      valueFiles:
        - '../../qa/values.yaml'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true