apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-eu-simple-env-helm-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:  
  project: gitops-helm-promotion
  source:
    path: kustomized_helm/overlays/staging-eu
    repoURL: https://github.com/lloydsmithjr03/gitops-helm-promotion
    targetRevision: HEAD
  destination:
    name: 'in-cluster'
    namespace: staging-helm-2
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
