apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-eu-simple-env-helm-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:  
  project: gitops-helm-promotion
  source:
    chart: simple-env-chart
    repoURL: 'https://github.com/lloydsmithjr03/simple-env-chart'
    targetRevision: 1.0.0
    helm:
      releaseName: staging-eu-simple-env-helm-2
      valueFiles:
        - '../../staging-eu/values.yaml'
  destination:
    name: 'in-cluster'
    namespace: staging-eu
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
