apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../helm_base

commonLabels:
  app.kubernetes.io/managed-by: argocd

namespace: qa-helm-2
namePrefix: qa-

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    labelSelector: "app.kubernetes.io/name=webserver-simple"
  path: patch/deployment.yml
- target:
    version: v1
    kind: Service
    labelSelector: "app.kubernetes.io/name=webserver-simple"
  path: patch/service.yml

resources:
  - namespace.yml