apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../helm_base

commonLabels:
  app.kubernetes.io/managed-by: argocd

namespace: qa-helm-2
namePrefix: qa-

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: qa-qa-simple-env-helm-2-webserver-simple
  path: patch/deployment.yml

resources:
  - namespace.yml