apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../helm_base

# commonLabels:
#   app.kubernetes.io/managed-by: argocd

namespace: qa-helm-2
namePrefix: qa-

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: qa-simple-deployment
  path: patch/deployment.yml
- target:
    version: v1
    kind: Service
    name: qa-simple-service
  path: patch/service.yml

resources:
  - namespace.yml
  - rollout.yml
  - service.yml

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml
