apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../helm_base

commonLabels:
  app.kubernetes.io/managed-by: argocd

namespace: prod-helm-2
namePrefix: prod-us-

resources:
  - namespace.yml