apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../helm_base

namespace: prod-helm-2
namePrefix: prod-us-

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: prod-us-simple-deployment
  path: patch/deployment.yml
- target:
    version: v1
    kind: Service
    name: prod-us-simple-service
  path: patch/service.yml

resources:
  - namespace.yml
  - rollout.yml

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml
