apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../helm_base

namespace: prod-helm-2
namePrefix: prod-us-

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    labelSelector: "app.kubernetes.io/instance=prod-us-simple-env-helm-2"
  path: patch/deployment.yml
- target:
    version: v1
    kind: Service
    labelSelector: "app.kubernetes.io/instance=prod-us-simple-env-helm-2"
  path: patch/service.yml

resources:
  - namespace.yml
  - rollout.yml

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

patchesStrategicMerge:
- |-
  apiVersion: argoproj.io/v1alpha1
  kind: Rollout
  metadata:
    name: simple-rollout
  spec:
    template: null