apiVersion: v1
kind: Service
metadata:
  name: {{ include "webserver-simple.fullname" . }}
  labels:
    {{- include "webserver-simple.labels" . | nindent 4 }}
spec:
  type: {{ .Values.global.service.type }}
  ports:
    - port: {{ .Values.global.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "webserver-simple.selectorLabels" . | nindent 4 }}
