apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../helm_base

commonLabels:
  app.kubernetes.io/managed-by: argocd

namespace: staging-helm-2
namePrefix: staging-eu-

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    labelSelector: "app.kubernetes.io/instance=staging-eu-simple-env-helm-2"
  path: patch/deployment.yml
- target:
    version: v1
    kind: Service
    labelSelector: "app.kubernetes.io/instance=staging-eu-simple-env-helm-2"
  path: patch/service.yml

resources:
  - rollout.yml

patchesStrategicMerge:
- |-
  apiVersion: argoproj.io/v1alpha1
  kind: Rollout
  metadata:
    name: simple-rollout
  spec:
    template: null