apiVersion: v1
kind: Service
metadata:
  name: preview-simple-service
spec:
  type: NodePort
  selector:
    app: trivial-go-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31201